/*
 * Copyright 2021 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(frame_spliter_f.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(cc827553c31189d1b41d9910b13e44b4)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <dslwp/frame_spliter_f.h>
// pydoc.h is automatically generated in the build directory
#include <frame_spliter_f_pydoc.h>

void bind_frame_spliter_f(py::module& m)
{

    using frame_spliter_f    = gr::dslwp::frame_spliter_f;


    py::class_<frame_spliter_f,
               gr::block,
               gr::basic_block,
               std::shared_ptr<frame_spliter_f>>(m, "frame_spliter_f", D(frame_spliter_f))

        .def(py::init(&frame_spliter_f::make),
           py::arg("key"),
           py::arg("frame_length"),
           D(frame_spliter_f,make)
        )
        



        ;




}








