/*
 * Copyright 2021 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(lrtc_mod_bc.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(b26ef00c20abf5c7576d71973a112f17)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <dslwp/lrtc_mod_bc.h>
// pydoc.h is automatically generated in the build directory
#include <lrtc_mod_bc_pydoc.h>

void bind_lrtc_mod_bc(py::module& m)
{

    using lrtc_mod_bc    = gr::dslwp::lrtc_mod_bc;


    py::class_<lrtc_mod_bc,
               gr::sync_interpolator,
               gr::block,
               gr::basic_block,
               std::shared_ptr<lrtc_mod_bc>>(m, "lrtc_mod_bc", D(lrtc_mod_bc))

        .def(py::init(&lrtc_mod_bc::make),
           D(lrtc_mod_bc,make)
        )
        



        ;




}








