/*
 * Copyright 2022 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(fft_estimator_cc.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(182f5f9a4c711b53cd8694dd0e784829)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/dslwp/fft_estimator_cc.h>
// pydoc.h is automatically generated in the build directory
#include <fft_estimator_cc_pydoc.h>

void bind_fft_estimator_cc(py::module& m)
{

    using fft_estimator_cc    = ::gr::dslwp::fft_estimator_cc;


    py::class_<fft_estimator_cc, gr::sync_block, gr::block, gr::basic_block,
        std::shared_ptr<fft_estimator_cc>>(m, "fft_estimator_cc", D(fft_estimator_cc))

        .def(py::init(&fft_estimator_cc::make),
           py::arg("fft_size"),
           py::arg("threshold"),
           py::arg("tap_len"),
           D(fft_estimator_cc,make)
        )
        



        ;




}








