/*
 * Copyright 2022 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(frame_spliter_c.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(0d568e12625894c8e1d3b8a02f586d62)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/dslwp/frame_spliter_c.h>
// pydoc.h is automatically generated in the build directory
#include <frame_spliter_c_pydoc.h>

void bind_frame_spliter_c(py::module& m)
{

    using frame_spliter_c    = ::gr::dslwp::frame_spliter_c;


    py::class_<frame_spliter_c, gr::sync_block, gr::block, gr::basic_block,
        std::shared_ptr<frame_spliter_c>>(m, "frame_spliter_c", D(frame_spliter_c))

        .def(py::init(&frame_spliter_c::make),
           py::arg("key"),
           py::arg("frame_length"),
           D(frame_spliter_c,make)
        )
        



        ;




}








