/*
 * Copyright 2022 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(program_tracking_cc.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(c312da57c0aa0aed42646ae63bf97cb4)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/dslwp/program_tracking_cc.h>
// pydoc.h is automatically generated in the build directory
#include <program_tracking_cc_pydoc.h>

void bind_program_tracking_cc(py::module& m)
{

    using program_tracking_cc    = ::gr::dslwp::program_tracking_cc;


    py::class_<program_tracking_cc, gr::sync_block, gr::block, gr::basic_block,
        std::shared_ptr<program_tracking_cc>>(m, "program_tracking_cc", D(program_tracking_cc))

        .def(py::init(&program_tracking_cc::make),
           py::arg("enable"),
           py::arg("timestamp"),
           py::arg("path"),
           py::arg("lon"),
           py::arg("lat"),
           py::arg("alt"),
           py::arg("fc"),
           py::arg("samp_rate"),
           py::arg("txrx"),
           py::arg("verbose"),
           D(program_tracking_cc,make)
        )
        



        ;




}








